project:
  type: website

website:
  title: "Spotify Dashboard"
  sidebar:
    content:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo,custom.scss]
    toc: true


